version: "3.8"
services:
  celery-beat:
    build:
      context: ./application/celery-beat
      dockerfile: Dockerfile.dev
    depends_on:
      - postgres
    env_file:
      - ./application/celery-beat/.env.dev
  postgres:
    restart: always
    build:
      context: ./application/database
      dockerfile: Dockerfile.dev
    expose:
      - "5432:5432"
    env_file:
      - ./application/database/.env.dev
