version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    depends_on:
      - redis
      - postgres

  celeryworker:
    build: .
    command: celery -A main.celery worker --loglevel=info
    env_file:
      - .env.dev
    depends_on:
      - redis
      - postgres

  celerybeat:
    build: .
    command: celery -A main.celery beat --loglevel=info
    env_file:
      - .env.dev
    depends_on:
      - redis
      - postgres

  postgres:
    build:
      context: ./postgresql
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.dev

  redis:
    image: redis:7-alpine
    restart: always

volumes:
  postgres_data:
